language: php
php:
  - "5.6"
  - "7.2"
  - "7.3"
script: 
    - sed -e "s#1931861#$PARTNER_ID#g" -e "s#83c3d4449a3abbe92ca5966f5f010eb4#$ADMIN_SECRET#g" -e "s#https://www.kaltura.com#https://www.kaltura.com#g" tests/config.template.ini > tests/config.ini 
    - cd tests && php run.php
