language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
script: cd tests && php run.php
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Jonathan.Kanarek@kaltura.com
      - Noam.Arad@kaltura.com
      - Nir.Belinky@kaltura.com
      - Elad.Cohen@kaltura.com
    on_success: change
    on_failure: always
