<?php
// ===================================================================================================
//                           _  __     _ _
//                          | |/ /__ _| | |_ _  _ _ _ __ _
//                          | ' </ _` | |  _| || | '_/ _` |
//                          |_|\_\__,_|_|\__|\_,_|_| \__,_|
//
// This file is part of the Kaltura Collaborative Media Suite which allows users
// to do with audio, video, and animation what Wiki platfroms allow them to do with
// text.
//
// Copyright (C) 2006-2017  Kaltura Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// @ignore
// ===================================================================================================

/**
 * @package Kaltura
 * @subpackage Client
 */
class Kaltura_Client_TypeMap
{
	private static $map = array(
		'KalturaAnnouncement' => 'Kaltura_Client_Type_Announcement',
		'KalturaAnnouncementFilter' => 'Kaltura_Client_Type_AnnouncementFilter',
		'KalturaAnnouncementListResponse' => 'Kaltura_Client_Type_AnnouncementListResponse',
		'KalturaApiActionPermissionItem' => 'Kaltura_Client_Type_ApiActionPermissionItem',
		'KalturaApiArgumentPermissionItem' => 'Kaltura_Client_Type_ApiArgumentPermissionItem',
		'KalturaApiParameterPermissionItem' => 'Kaltura_Client_Type_ApiParameterPermissionItem',
		'KalturaAppToken' => 'Kaltura_Client_Type_AppToken',
		'KalturaAsset' => 'Kaltura_Client_Type_Asset',
		'KalturaAssetComment' => 'Kaltura_Client_Type_AssetComment',
		'KalturaAssetCommentFilter' => 'Kaltura_Client_Type_AssetCommentFilter',
		'KalturaAssetCommentListResponse' => 'Kaltura_Client_Type_AssetCommentListResponse',
		'KalturaAssetFileContext' => 'Kaltura_Client_Type_AssetFileContext',
		'KalturaAssetFilter' => 'Kaltura_Client_Type_AssetFilter',
		'KalturaAssetHistory' => 'Kaltura_Client_Type_AssetHistory',
		'KalturaAssetHistoryFilter' => 'Kaltura_Client_Type_AssetHistoryFilter',
		'KalturaAssetHistoryListResponse' => 'Kaltura_Client_Type_AssetHistoryListResponse',
		'KalturaAssetListResponse' => 'Kaltura_Client_Type_AssetListResponse',
		'KalturaAssetStatistics' => 'Kaltura_Client_Type_AssetStatistics',
		'KalturaAssetStatisticsListResponse' => 'Kaltura_Client_Type_AssetStatisticsListResponse',
		'KalturaAssetStatisticsQuery' => 'Kaltura_Client_Type_AssetStatisticsQuery',
		'KalturaBaseAssetInfo' => 'Kaltura_Client_Type_BaseAssetInfo',
		'KalturaBaseChannel' => 'Kaltura_Client_Type_BaseChannel',
		'KalturaBaseOTTUser' => 'Kaltura_Client_Type_BaseOTTUser',
		'KalturaBillingPartnerConfig' => 'Kaltura_Client_Type_BillingPartnerConfig',
		'KalturaBillingResponse' => 'Kaltura_Client_Type_BillingResponse',
		'KalturaBillingTransaction' => 'Kaltura_Client_Type_BillingTransaction',
		'KalturaBillingTransactionListResponse' => 'Kaltura_Client_Type_BillingTransactionListResponse',
		'KalturaBookmark' => 'Kaltura_Client_Type_Bookmark',
		'KalturaBookmarkFilter' => 'Kaltura_Client_Type_BookmarkFilter',
		'KalturaBookmarkListResponse' => 'Kaltura_Client_Type_BookmarkListResponse',
		'KalturaBookmarkPlayerData' => 'Kaltura_Client_Type_BookmarkPlayerData',
		'KalturaBooleanValue' => 'Kaltura_Client_Type_BooleanValue',
		'KalturaBundleFilter' => 'Kaltura_Client_Type_BundleFilter',
		'KalturaBuzzScore' => 'Kaltura_Client_Type_BuzzScore',
		'KalturaCDNAdapterProfile' => 'Kaltura_Client_Type_CDNAdapterProfile',
		'KalturaCDNAdapterProfileListResponse' => 'Kaltura_Client_Type_CDNAdapterProfileListResponse',
		'KalturaCDNPartnerSettings' => 'Kaltura_Client_Type_CDNPartnerSettings',
		'KalturaCDVRAdapterProfile' => 'Kaltura_Client_Type_CDVRAdapterProfile',
		'KalturaCDVRAdapterProfileListResponse' => 'Kaltura_Client_Type_CDVRAdapterProfileListResponse',
		'KalturaCatalogWithHolder' => 'Kaltura_Client_Type_CatalogWithHolder',
		'KalturaChannel' => 'Kaltura_Client_Type_Channel',
		'KalturaChannelEnrichmentHolder' => 'Kaltura_Client_Type_ChannelEnrichmentHolder',
		'KalturaChannelExternalFilter' => 'Kaltura_Client_Type_ChannelExternalFilter',
		'KalturaChannelFilter' => 'Kaltura_Client_Type_ChannelFilter',
		'KalturaCountry' => 'Kaltura_Client_Type_Country',
		'KalturaCoupon' => 'Kaltura_Client_Type_Coupon',
		'KalturaCouponsGroup' => 'Kaltura_Client_Type_CouponsGroup',
		'KalturaDeviceFamilyBase' => 'Kaltura_Client_Type_DeviceFamilyBase',
		'KalturaDevicePin' => 'Kaltura_Client_Type_DevicePin',
		'KalturaDeviceRegistrationStatusHolder' => 'Kaltura_Client_Type_DeviceRegistrationStatusHolder',
		'KalturaDiscountModule' => 'Kaltura_Client_Type_DiscountModule',
		'KalturaDoubleValue' => 'Kaltura_Client_Type_DoubleValue',
		'KalturaEntitlement' => 'Kaltura_Client_Type_Entitlement',
		'KalturaEntitlementFilter' => 'Kaltura_Client_Type_EntitlementFilter',
		'KalturaEntitlementListResponse' => 'Kaltura_Client_Type_EntitlementListResponse',
		'KalturaExportTask' => 'Kaltura_Client_Type_ExportTask',
		'KalturaExportTaskFilter' => 'Kaltura_Client_Type_ExportTaskFilter',
		'KalturaExportTaskListResponse' => 'Kaltura_Client_Type_ExportTaskListResponse',
		'KalturaExternalChannelProfile' => 'Kaltura_Client_Type_ExternalChannelProfile',
		'KalturaExternalChannelProfileListResponse' => 'Kaltura_Client_Type_ExternalChannelProfileListResponse',
		'KalturaExternalReceipt' => 'Kaltura_Client_Type_ExternalReceipt',
		'KalturaFacebookSocial' => 'Kaltura_Client_Type_FacebookSocial',
		'KalturaFavorite' => 'Kaltura_Client_Type_Favorite',
		'KalturaFavoriteFilter' => 'Kaltura_Client_Type_FavoriteFilter',
		'KalturaFavoriteListResponse' => 'Kaltura_Client_Type_FavoriteListResponse',
		'KalturaFeed' => 'Kaltura_Client_Type_Feed',
		'KalturaFilter' => 'Kaltura_Client_Type_Filter',
		'KalturaFilterPager' => 'Kaltura_Client_Type_FilterPager',
		'KalturaFollowDataBase' => 'Kaltura_Client_Type_FollowDataBase',
		'KalturaFollowTvSeries' => 'Kaltura_Client_Type_FollowTvSeries',
		'KalturaFollowTvSeriesFilter' => 'Kaltura_Client_Type_FollowTvSeriesFilter',
		'KalturaFollowTvSeriesListResponse' => 'Kaltura_Client_Type_FollowTvSeriesListResponse',
		'KalturaGroupPermission' => 'Kaltura_Client_Type_GroupPermission',
		'KalturaHomeNetwork' => 'Kaltura_Client_Type_HomeNetwork',
		'KalturaHomeNetworkListResponse' => 'Kaltura_Client_Type_HomeNetworkListResponse',
		'KalturaHousehold' => 'Kaltura_Client_Type_Household',
		'KalturaHouseholdDevice' => 'Kaltura_Client_Type_HouseholdDevice',
		'KalturaHouseholdDeviceFamilyLimitations' => 'Kaltura_Client_Type_HouseholdDeviceFamilyLimitations',
		'KalturaHouseholdLimitations' => 'Kaltura_Client_Type_HouseholdLimitations',
		'KalturaHouseholdPaymentGateway' => 'Kaltura_Client_Type_HouseholdPaymentGateway',
		'KalturaHouseholdPaymentGatewayListResponse' => 'Kaltura_Client_Type_HouseholdPaymentGatewayListResponse',
		'KalturaHouseholdPaymentMethod' => 'Kaltura_Client_Type_HouseholdPaymentMethod',
		'KalturaHouseholdPaymentMethodListResponse' => 'Kaltura_Client_Type_HouseholdPaymentMethodListResponse',
		'KalturaHouseholdPremiumService' => 'Kaltura_Client_Type_HouseholdPremiumService',
		'KalturaHouseholdPremiumServiceListResponse' => 'Kaltura_Client_Type_HouseholdPremiumServiceListResponse',
		'KalturaHouseholdQuota' => 'Kaltura_Client_Type_HouseholdQuota',
		'KalturaHouseholdUser' => 'Kaltura_Client_Type_HouseholdUser',
		'KalturaHouseholdWithHolder' => 'Kaltura_Client_Type_HouseholdWithHolder',
		'KalturaInboxMessage' => 'Kaltura_Client_Type_InboxMessage',
		'KalturaInboxMessageFilter' => 'Kaltura_Client_Type_InboxMessageFilter',
		'KalturaInboxMessageListResponse' => 'Kaltura_Client_Type_InboxMessageListResponse',
		'KalturaIntegerValue' => 'Kaltura_Client_Type_IntegerValue',
		'KalturaItemPrice' => 'Kaltura_Client_Type_ItemPrice',
		'KalturaItemPriceListResponse' => 'Kaltura_Client_Type_ItemPriceListResponse',
		'KalturaKeyValue' => 'Kaltura_Client_Type_KeyValue',
		'KalturaLicensedUrl' => 'Kaltura_Client_Type_LicensedUrl',
		'KalturaLicensedUrlBaseRequest' => 'Kaltura_Client_Type_LicensedUrlBaseRequest',
		'KalturaLicensedUrlEpgRequest' => 'Kaltura_Client_Type_LicensedUrlEpgRequest',
		'KalturaLicensedUrlMediaRequest' => 'Kaltura_Client_Type_LicensedUrlMediaRequest',
		'KalturaLicensedUrlRecordingRequest' => 'Kaltura_Client_Type_LicensedUrlRecordingRequest',
		'KalturaListResponse' => 'Kaltura_Client_Type_ListResponse',
		'KalturaLoginResponse' => 'Kaltura_Client_Type_LoginResponse',
		'KalturaLoginSession' => 'Kaltura_Client_Type_LoginSession',
		'KalturaLongValue' => 'Kaltura_Client_Type_LongValue',
		'KalturaMediaAsset' => 'Kaltura_Client_Type_MediaAsset',
		'KalturaMediaFile' => 'Kaltura_Client_Type_MediaFile',
		'KalturaMediaImage' => 'Kaltura_Client_Type_MediaImage',
		'KalturaMessageTemplate' => 'Kaltura_Client_Type_MessageTemplate',
		'KalturaNotificationsPartnerSettings' => 'Kaltura_Client_Type_NotificationsPartnerSettings',
		'KalturaNotificationsSettings' => 'Kaltura_Client_Type_NotificationsSettings',
		'KalturaOSSAdapterBaseProfile' => 'Kaltura_Client_Type_OSSAdapterBaseProfile',
		'KalturaOSSAdapterProfile' => 'Kaltura_Client_Type_OSSAdapterProfile',
		'KalturaOTTCategory' => 'Kaltura_Client_Type_OTTCategory',
		'KalturaOTTUser' => 'Kaltura_Client_Type_OTTUser',
		'KalturaOTTUserFilter' => 'Kaltura_Client_Type_OTTUserFilter',
		'KalturaOTTUserListResponse' => 'Kaltura_Client_Type_OTTUserListResponse',
		'KalturaOTTUserType' => 'Kaltura_Client_Type_OTTUserType',
		'KalturaPPVItemPriceDetails' => 'Kaltura_Client_Type_PPVItemPriceDetails',
		'KalturaParentalRule' => 'Kaltura_Client_Type_ParentalRule',
		'KalturaParentalRuleFilter' => 'Kaltura_Client_Type_ParentalRuleFilter',
		'KalturaParentalRuleListResponse' => 'Kaltura_Client_Type_ParentalRuleListResponse',
		'KalturaPartnerConfiguration' => 'Kaltura_Client_Type_PartnerConfiguration',
		'KalturaPartnerConfigurationHolder' => 'Kaltura_Client_Type_PartnerConfigurationHolder',
		'KalturaPaymentGatewayBaseProfile' => 'Kaltura_Client_Type_PaymentGatewayBaseProfile',
		'KalturaPaymentGatewayConfiguration' => 'Kaltura_Client_Type_PaymentGatewayConfiguration',
		'KalturaPaymentGatewayProfile' => 'Kaltura_Client_Type_PaymentGatewayProfile',
		'KalturaPaymentGatewayProfileListResponse' => 'Kaltura_Client_Type_PaymentGatewayProfileListResponse',
		'KalturaPaymentMethodProfile' => 'Kaltura_Client_Type_PaymentMethodProfile',
		'KalturaPaymentMethodProfileFilter' => 'Kaltura_Client_Type_PaymentMethodProfileFilter',
		'KalturaPaymentMethodProfileListResponse' => 'Kaltura_Client_Type_PaymentMethodProfileListResponse',
		'KalturaPermission' => 'Kaltura_Client_Type_Permission',
		'KalturaPermissionItem' => 'Kaltura_Client_Type_PermissionItem',
		'KalturaPersonalFeed' => 'Kaltura_Client_Type_PersonalFeed',
		'KalturaPersonalFeedFilter' => 'Kaltura_Client_Type_PersonalFeedFilter',
		'KalturaPersonalFeedListResponse' => 'Kaltura_Client_Type_PersonalFeedListResponse',
		'KalturaPin' => 'Kaltura_Client_Type_Pin',
		'KalturaPinResponse' => 'Kaltura_Client_Type_PinResponse',
		'KalturaPlayerAssetData' => 'Kaltura_Client_Type_PlayerAssetData',
		'KalturaPpv' => 'Kaltura_Client_Type_Ppv',
		'KalturaPpvPrice' => 'Kaltura_Client_Type_PpvPrice',
		'KalturaPremiumService' => 'Kaltura_Client_Type_PremiumService',
		'KalturaPreviewModule' => 'Kaltura_Client_Type_PreviewModule',
		'KalturaPrice' => 'Kaltura_Client_Type_Price',
		'KalturaPriceDetails' => 'Kaltura_Client_Type_PriceDetails',
		'KalturaPricePlan' => 'Kaltura_Client_Type_PricePlan',
		'KalturaProductPrice' => 'Kaltura_Client_Type_ProductPrice',
		'KalturaProductPriceFilter' => 'Kaltura_Client_Type_ProductPriceFilter',
		'KalturaProductPriceListResponse' => 'Kaltura_Client_Type_ProductPriceListResponse',
		'KalturaProductsPriceListResponse' => 'Kaltura_Client_Type_ProductsPriceListResponse',
		'KalturaProgramAsset' => 'Kaltura_Client_Type_ProgramAsset',
		'KalturaPurchase' => 'Kaltura_Client_Type_Purchase',
		'KalturaPurchaseBase' => 'Kaltura_Client_Type_PurchaseBase',
		'KalturaPurchaseSession' => 'Kaltura_Client_Type_PurchaseSession',
		'KalturaPurchaseSettings' => 'Kaltura_Client_Type_PurchaseSettings',
		'KalturaRecommendationProfile' => 'Kaltura_Client_Type_RecommendationProfile',
		'KalturaRecommendationProfileListResponse' => 'Kaltura_Client_Type_RecommendationProfileListResponse',
		'KalturaRecording' => 'Kaltura_Client_Type_Recording',
		'KalturaRecordingFilter' => 'Kaltura_Client_Type_RecordingFilter',
		'KalturaRecordingListResponse' => 'Kaltura_Client_Type_RecordingListResponse',
		'KalturaRegion' => 'Kaltura_Client_Type_Region',
		'KalturaRegionFilter' => 'Kaltura_Client_Type_RegionFilter',
		'KalturaRegionListResponse' => 'Kaltura_Client_Type_RegionListResponse',
		'KalturaRegionalChannel' => 'Kaltura_Client_Type_RegionalChannel',
		'KalturaRegistryResponse' => 'Kaltura_Client_Type_RegistryResponse',
		'KalturaRegistrySettings' => 'Kaltura_Client_Type_RegistrySettings',
		'KalturaRegistrySettingsListResponse' => 'Kaltura_Client_Type_RegistrySettingsListResponse',
		'KalturaRelatedExternalFilter' => 'Kaltura_Client_Type_RelatedExternalFilter',
		'KalturaRelatedFilter' => 'Kaltura_Client_Type_RelatedFilter',
		'KalturaSearchAssetFilter' => 'Kaltura_Client_Type_SearchAssetFilter',
		'KalturaSearchExternalFilter' => 'Kaltura_Client_Type_SearchExternalFilter',
		'KalturaSeriesRecording' => 'Kaltura_Client_Type_SeriesRecording',
		'KalturaSeriesRecordingFilter' => 'Kaltura_Client_Type_SeriesRecordingFilter',
		'KalturaSeriesRecordingListResponse' => 'Kaltura_Client_Type_SeriesRecordingListResponse',
		'KalturaSession' => 'Kaltura_Client_Type_Session',
		'KalturaSessionInfo' => 'Kaltura_Client_Type_SessionInfo',
		'KalturaSlimAsset' => 'Kaltura_Client_Type_SlimAsset',
		'KalturaSlimAssetInfoWrapper' => 'Kaltura_Client_Type_SlimAssetInfoWrapper',
		'KalturaSocial' => 'Kaltura_Client_Type_Social',
		'KalturaSocialConfig' => 'Kaltura_Client_Type_SocialConfig',
		'KalturaSocialResponse' => 'Kaltura_Client_Type_SocialResponse',
		'KalturaSocialUser' => 'Kaltura_Client_Type_SocialUser',
		'KalturaStringValue' => 'Kaltura_Client_Type_StringValue',
		'KalturaStringValueArray' => 'Kaltura_Client_Type_StringValueArray',
		'KalturaSubscription' => 'Kaltura_Client_Type_Subscription',
		'KalturaSubscriptionFilter' => 'Kaltura_Client_Type_SubscriptionFilter',
		'KalturaSubscriptionListResponse' => 'Kaltura_Client_Type_SubscriptionListResponse',
		'KalturaSubscriptionPrice' => 'Kaltura_Client_Type_SubscriptionPrice',
		'KalturaTimeShiftedTvPartnerSettings' => 'Kaltura_Client_Type_TimeShiftedTvPartnerSettings',
		'KalturaTopic' => 'Kaltura_Client_Type_Topic',
		'KalturaTopicFilter' => 'Kaltura_Client_Type_TopicFilter',
		'KalturaTopicListResponse' => 'Kaltura_Client_Type_TopicListResponse',
		'KalturaTransaction' => 'Kaltura_Client_Type_Transaction',
		'KalturaTransactionHistoryFilter' => 'Kaltura_Client_Type_TransactionHistoryFilter',
		'KalturaTransactionStatus' => 'Kaltura_Client_Type_TransactionStatus',
		'KalturaTranslationToken' => 'Kaltura_Client_Type_TranslationToken',
		'KalturaUsageModule' => 'Kaltura_Client_Type_UsageModule',
		'KalturaUserAssetRule' => 'Kaltura_Client_Type_UserAssetRule',
		'KalturaUserAssetRuleFilter' => 'Kaltura_Client_Type_UserAssetRuleFilter',
		'KalturaUserAssetRuleListResponse' => 'Kaltura_Client_Type_UserAssetRuleListResponse',
		'KalturaUserAssetsListItem' => 'Kaltura_Client_Type_UserAssetsListItem',
		'KalturaUserLoginPin' => 'Kaltura_Client_Type_UserLoginPin',
		'KalturaUserRole' => 'Kaltura_Client_Type_UserRole',
		'KalturaUserRoleFilter' => 'Kaltura_Client_Type_UserRoleFilter',
		'KalturaUserRoleListResponse' => 'Kaltura_Client_Type_UserRoleListResponse',
		'KalturaValue' => 'Kaltura_Client_Type_Value',
	);
	
	public static function getZendType($kalturaType)
	{
		if(isset(self::$map[$kalturaType]))
			return self::$map[$kalturaType];
		return null;
	}
}
